local o = vim.opt
o.ignorecase = true                -- Ignore case in search patterns
o.smartcase = true                 -- Ignore case in search patterns if no upper case
o.number = true                    -- Show line numbers
o.relativenumber = true            -- Use relative line numbers
o.hlsearch = true                  -- Highlight search matches
o.mouse = "a"                      -- Allow mouse usage
o.splitbelow = true                -- Horizontal splits go below current window
o.splitright = true                -- Vertical splits go to the right of current window
o.cursorline = true                -- Highlight current line
